### ISSUE TITLE
질문이 있습니다~

### ISSUE THREAD

**Issue by minji100** [yamoo9/FDC#16]
![2017-03-06 3 05 09](https://cloud.githubusercontent.com/assets/25610649/23598520/51c2d2b4-027e-11e7-9d6c-c5b6160bdb66.png)

1080px이하에서 가운데 로고와 텍스트 이미지를 가로사이즈에 맞게 줄어들게 하고싶어요 (양옆 마진 있게)
어떤 코드를 어디에 써야하나요 ㅠㅠ?
[coming soon.zip](https://github.com/yamoo9/FDC/files/820265/coming.soon.zip)

**Comment by yamoo9** [comment]
안녕하세요. @minji100 님 ^^

올려주신 코드를 살펴보니.. 금기시 되는 코드가 여기 저기 많이 사용 되었네요..
왜 이런 코드를 사용하면 안되는지 직접 뵙고 이야기 드릴께요. ㅠㅡㅠ

수정해야 할 곳이 많지만.. 우선은 질문 주신 이미지 사이즈 조정 문제만 불을 꺼보도록 하죠.
아래 코드는 제가 수정한 곳입니다. 이와 같이 변경하면 요구하신 사항이 적용될거에요. ^^

```css
/* intro */
#intro {
  /*position: relative;*/
  /*display: table;*/
  width: 100%;
  height: 100%;
  background: url(../img/bg.jpg) no-repeat 50% 50%;
  background-size: cover;
  text-align: center;
  letter-spacing: 0.1em;
  font-size: 20px;
  color: #fff
}
#intro .intro_info {
  /*display: table-cell;*/
  /*padding: 2% 0;*/
  vertical-align: middle
}
```

```css
@media screen and (max-width: 1080px) {

  #intro h1 {
    width: 100%
  }

  .logo a {
    display: block;
  }

  .logo img {
    width: 50vw;
    height: auto;
  }

}
```
