### ISSUE TITLE
FDC 4기 김태연 과제 : 움직임 마무리

### ISSUE THREAD

**Issue by tykimdesign** [yamoo9/FDC#31]
[원숭이배너 움직임](https://tykimdesign.github.io/day10_HW/banner_02.html)

이전 수업시간에했던 움직임/효과 과제 업로드합니다 :)

**Comment by yamoo9** [comment]
태연님 ^^ 과제 또 1등! Feel 받으셨군요~ Good!

마우스가 올라갔을 때 애니메이션이 실행되는데
마우스가 빠져나가면 뚝! 끊기듯 애니메이션이 사라지죠?

아래 예시처럼 `.topbanner:hover .apes`에 설정된 `transition: all 0.4s ease-out;` 코드를

```css
.topbanner.fin .apes, .topbanner:hover .apes {
  opacity: 100;
  transition: all 0.4s ease-out;
}
```

`.apes`로 변경하면, 애니메이션이 끊겨보이지 않을 거에요 ^^ 

```css
.apes {
   transition: all 0.4s ease-out;  /* ⬅︎ */
}

.topbanner.fin .apes, .topbanner:hover .apes {
  opacity: 100;
}
```

다른 부분도 마찬가지! 
시도해보세요!
