### ISSUE TITLE
FDC 4th_신수정 과제 제출

### ISSUE THREAD

**Issue by shinsu91** [yamoo9/FDC#32]
1. 원숭이 배너
https://shinsu91.github.io/Day10/banner-assets/banner.html

2. 영화포스터
https://shinsu91.github.io/Day11/poster/poster.html

- body에 height: 100vh; 을 기입,
  추가적으로 background-repeat: no-repeat; / background-size: cover; 이 소스도 넣어봤는데요,,
  이미지가 온전히 보여지지 않습니다,, 소스 확인 부탁드립니다.
- 상단에 JAKE GYLLENHAAL 문구가 들어갔는데, 적용되지 않습니다,,,ㅠㅠ 소스 확인 부탁드릴게요!
- 누끼를 딴 인물이 총 13명인데요~ 
   큰사람부터 작은 사람까지 차례대로 딴!딴!딴! 나오게끔 CSS에서 작업 할 수 있나요?

**Comment by yamoo9** [comment]
포스터 사이즈가 커서 이미지가 보이도록 수정 하려면 Scale 값을 조정하여 보이게 하거나,
CSS 레이아웃 코드를 손봐서 수정하면 될 거 같아요 ^^

```css
.wrap { 
   transform: scale(0.75); 
}
```

![](http://i65.tinypic.com/2rgfc0p.png)

그리고 JAKE GYLLENHAAL 텍스트는 현재 이미지 뒤에 감춰져 있는데
이는 position 속성을 이용하여 이미지 위로 올릴 수 있어요. 

```css
.copy { 
   position: relative;
   z-index: 100;
}
```

![](http://i63.tinypic.com/4tlqp3.png)

마지막으로 애니메이션은 별도로 설명하고, 코드 보실 수 있도록 해 드릴께요 ^^
